name: Build Android APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the APK
        run: ./gradlew assembleRelease

      - name: Restore keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > my-release-key.keystore

      - name: Sign APK
        run: |
          jarsigner -verbose -keystore my-release-key.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}
          zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: dgs-shop-app-release-v2.apk
